export const ACTION = {
  REQUEST: 'REQUEST',
  GET_CITIES_SUCCESS: 'GET_CITIES_SUCCESS',
  GET_CURRENT_CITY_SUCCESS: 'GET_CURRENT_CITY_SUCCESS',
  ADD_NEW_CITY_SUCCESS: 'ADD_NEW_CITY_SUCCESS',
  DELETE_CITY_SUCCESS: 'DELETE_CITY_SUCCESS',
  ERROR: 'ERROR',
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
};
